INSERT INTO DEMO(name,EMAIL)
VALUES('SWETHA','abc@gmail.com');
INSERT INTO DEMO1(NAME,REGNO)
VALUES('PRIYA','111');
INSERT INTO DEMO2(NAME,AGE)
VALUES('SNEGA','20');
INSERT INTO DEMO4(NAME,MARK)
VALUES('RISHI','91');
INSERT INTO DEMO5(NAME,ROLLNO)
VALUES('KAVI','22222');



