INSERT INTO TEST1 (name,dept)
VALUES ('SANDHIYA','COMPUTER SCIENCE ENGINEERING');
INSERT INTO TEST2 (Nation,state)
VALUES ('INDIA','TAMILNADU');
INSERT INTO TEST3 (age,goal)
VALUES ('21','SOFTWARE ENGINEERING');
INSERT INTO TEST4 (Location,pincode,doorno,street)
VALUES ('KARUR','639003','33','SURIYANAGAR');
INSERT INTO TEST5 (BLOODGRP,CONTACTNO,REGISTERNO,DESIGNATION,GENDER)
VALUES ('AB','93455685','19104086','STUDENT','FEMALE');
UPDATE TEST5
SET BLOODGRP='O',CONTACTNO='96778468';
DELETE FROM TEST3;